services:
  user-db:
    image: postgres:15
    container_name: user-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users_db
    ports:
      - "5432:5432"
    volumes:
      - user-db-data:/var/lib/postgresql/data

  workout-db:
    image: postgres:15
    container_name: workout-db
    environment:
      POSTGRES_USER: workout
      POSTGRES_PASSWORD: password
      POSTGRES_DB: workouts_db
    ports:
      - "5433:5432"
    volumes:
      - workout-db-data:/var/lib/postgresql/data

  session-db:
    image: postgres:15
    container_name: session-db
    environment:
      POSTGRES_USER: session
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sessions_db
    ports:
      - "5434:5432"
    volumes:
      - session-db-data:/var/lib/postgresql/data

  user-service:
    build:
      context: .
      dockerfile: ./user-service/Dockerfile
    container_name: user-service
    ports:
      - "50051:50051"
    depends_on:
      - user-db
    environment:
      DB_HOST: user-db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: users_db

  workout-service:
    build:
      context: .
      dockerfile: ./workout-service/Dockerfile
    container_name: workout-service
    ports:
      - "50052:50052"
    depends_on:
      - workout-db
      - user-service
    environment:
      DB_HOST: workout-db
      DB_PORT: 5432
      DB_USER: workout
      DB_PASSWORD: password
      DB_NAME: workouts_db

  session-service:
    build:
      context: .
      dockerfile: ./session-service/Dockerfile
    container_name: session-service
    ports:
      - "50053:50053"
    depends_on:
      - session-db
      - workout-service
    environment:
      DB_HOST: session-db
      DB_PORT: 5432
      DB_USER: session
      DB_PASSWORD: password
      DB_NAME: sessions_db

  api-gateway:
    build:
      context: .
      dockerfile: ./api-gateway/Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - workout-service
      - session-service
    environment:
      GATEWAY_PORT: 8080
      USER_SERVICE_ADDR: user-service:50051
      WORKOUT_SERVICE_ADDR: workout-service:50052
      SESSION_SERVICE_ADDR: session-service:50053

volumes:
  user-db-data:
  workout-db-data:
  session-db-data:
